### ISSUE TITLE
Jobs section is broken

### ISSUE THREAD

**Issue by edennis** [barcelonarb/bcnonrails#3]
It's too bad the jobs section doesn't work as it's one of the top 3 hits on google if you're looking for a RoR job in spain.  :(  Glad to help out if someone would give me a snippet of the server log so we could find out what's going wrong.

**Comment by vcastellm** [comment]
https://github.com/barcelonarb/bcnonrails/commit/50a5056dd99dab785c4b35bcc3ea45bed33b1b1b

Fixed, jobs from non existing companies must be removed too.

Thanks

On Fri, Jul 19, 2013 at 3:45 PM, Erick Dennis notifications@github.comwrote:

> It's too bad the jobs section doesn't work as it's one of the top 3 hits
> on google if you're looking for a RoR job in spain. :( Glad to help out if
> someone would give me a snippet of the server log so we could find out
> what's going wrong.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/barcelonarb/bcnonrails/issues/3
> .

## 

## 

V

**Comment by edennis** [comment]
Great! Thanks!
